// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfyGHxXijDMLys7gzVYJ2DA5J1T80sw-k',
    appId: '1:301855838376:android:da8fd40ee0c58dcea6329d',
    messagingSenderId: '301855838376',
    projectId: 'com-tam-revi',
    storageBucket: 'com-tam-revi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHuDwEPx-IdSHygoF4t_aU-Tv6uWc75xI',
    appId: '1:301855838376:ios:707451cd2680d0c3a6329d',
    messagingSenderId: '301855838376',
    projectId: 'com-tam-revi',
    storageBucket: 'com-tam-revi.appspot.com',
    androidClientId: '301855838376-29aakpakh4uuub3j5npl1lb3hler2kr3.apps.googleusercontent.com',
    iosClientId: '301855838376-o4vo90n4aksrfnt0amr2lq8v2bhplb2s.apps.googleusercontent.com',
    iosBundleId: 'com.tamrevi',
  );
}
